### ISSUE TITLE
Add size limit option for esbuild-plugin-filesize

### ISSUE THREAD

**Issue by mochaaP** [LinbuduLab/nx-plugins#55]
Adding a size limit option, familiar to [size-limit](https://github.com/ai/size-limit), can make this plugin an alternative to it with better esbuild integration.

Thanks for your excellent work on this!

**Comment by linbudu599** [comment]
Thanks for your suggestions! I will refine it this weekend.

**Comment by linbudu599** [comment]
Hi, I've checked the size-limit plugin and think a `size-limit` option to throw warnings is indeed useful, but I'm not sure where and how to put it on. Shall we add a `size-limit` for only origin output size? Or provide unique one for every compressed size itself?
