### ISSUE TITLE
esbuild-plugin-copy: keep directory structure

### ISSUE THREAD

**Issue by jaschaio** [LinbuduLab/nx-plugins#57]
How do I keep the directory structure when copying?

```js
assets: [ {
    from: [ './node_modules/tinymce/skins/**/*' ],
    to: [ './js/skins' ],
} ]
```

This merges all files within the root directory `/js/skins/` and doesn't preserve the original directory structure.

**Comment by linbudu599** [comment]
The easiest way is to configure it explicitly:

```javascript
assets: [
          {
            from: ["./node_modules/tinymce/themes/mobile/*"],
            to: ["./js/skins/mobile"],
          },
          {
            from: ["./node_modules/tinymce/themes/silver/*"],
            to: ["./js/skins/silver"],
          },
        ],```

**Comment by jaschaio** [comment]
Yeah thats the solution I came up with but it's pretty ugly once you have a handful of subdirectories to copy as well.

**Comment by linbudu599** [comment]
This feature is added in latest version 0.6.0, I'll add the related example to documentation soon.

**Comment by linbudu599** [comment]
This is support at latest version `1.0.1`, documentation is updated too, please refers to [esbuild-plugin-copy#preserve-file-structure](https://nx-plugins.netlify.app/derived/esbuild.html#preserve-file-structure)
