### ISSUE TITLE
如何用在vite里面

### ISSUE THREAD

**Issue by agileago** [LinbuduLab/nx-plugins#59]
esbuild的插件怎么在vite里面使用

**Comment by linbudu599** [comment]
看起来目前 Vite 只用了 ESBuild 的 transform API，transform API 是不支持配置插件的（只有 build API 支持），你估计需要自己 fork 逻辑改造成 Rollup/Vite 这种插件体系。为什么这么做则是因为 Vite 只是使用 ESBuild transform 来独立的编译文件，而不是去做 bundle 啥的。

**Comment by agileago** [comment]
了解了
