### ISSUE TITLE
Can't install some dependencies due to esbuild peer version

### ISSUE THREAD

**Issue by pherval** [LinbuduLab/nx-plugins#64]
some packages can't be installed with version `esbuild 0.14`.  I tried `esbuild-plugin-node-externals ` and `esbuild-plugin-run `, the problem seems to be the `peerDependecy` that is incompatible.

**Comment by un-focused** [comment]
I am getting this issue too

**Comment by un-focused** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: finad_webapp@0.0.1
npm ERR! Found: esbuild@0.14.21
npm ERR! node_modules/esbuild
npm ERR!   dev esbuild@"^0.14.21" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@"^0.12.25" from esbuild-plugin-run@0.2.0
npm ERR! node_modules/esbuild-plugin-run
npm ERR!   dev esbuild-plugin-run@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! `

**Comment by linbudu599** [comment]
Thanks for report and sorry for the late response, I'll got this fixed this weekend.

**Comment by linbudu599** [comment]
@un-focused @pherval Plugin's ESBuild peer version has been bumped to `^0.14.0` now, so it should works normally.

**Comment by pherval** [comment]
> @un-focused @pherval Plugin's ESBuild peer version has been bumped to `^0.14.0` now, so it should works normally.

@linbudu599 thanks a lot. Do you need any help? I just don't have familiarity with pnpm yet, other than that I think I can help

**Comment by linbudu599** [comment]
> > @un-focused @pherval Plugin's ESBuild peer version has been bumped to `^0.14.0` now, so it should works normally.
> 
> @linbudu599 thanks a lot. Do you need any help? I just don't have familiarity with pnpm yet, other than that I think I can help

Thanks! You can raise an issue when you encounter this kind of problem again, or just submit a pr to update version (I will gradually add the contributing guide, as I'm still refining its workflow).
