### ISSUE TITLE
Bump version of NX plugin libraries

### ISSUE THREAD

**Issue by gioragutt** [LinbuduLab/nx-plugins#65]
Hi @linbudu599 and @alykamb, there was recently an update that makes the nx plugins use NX v13 dependencies, which is great.
However, there was no version bump after the change so users cannot use the plugins in Nx v13.

Do you mind performing a version bump on the NX plugin libraries?

[Reference for problems](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1645529428346599)

**Comment by juan-calle** [comment]
> Hi @linbudu599 and @alykamb, there was recently an update that makes the nx plugins use NX v13 dependencies, which is great. However, there was no version bump after the change so users cannot use the plugins in Nx v13.
> 
> Do you mind performing a version bump on the NX plugin libraries?
> 
> [Reference for problems](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1645529428346599)

I second this! It'd be great to be able to use these plugins again with Nx v13!

Thanks @gioragutt  for raising this issue. Hopefully getting it fixed will help many others :)

**Comment by linbudu599** [comment]
Thans for report! I'll perform a total refactor & enhancement on this project at this weekend.

**Comment by juan-calle** [comment]
Thank you!
