### ISSUE TITLE
Supress clean files output

### ISSUE THREAD

**Issue by jasonwilliams** [LinbuduLab/nx-plugins#76]
Hey great plugin!

When the [esbuild-clean-plugin](https://github.com/LinbuduLab/nx-plugins/tree/main/packages/esbuild-plugin-clean) cleans its files it prints out a list of all the files cleaned. I don't really need this information it just spams the logs. Can we have an option to supress it?

I didn't see anything obvious in https://nx-plugins.netlify.app/derived/esbuild.html#clean

I feel like this should be off by default then switched on by a `verbose` mode or something? Just a suggestion

**Comment by linbudu599** [comment]
Sure, I created this plugin in a great hurry, thank you for your feedback, I will make adjustments immediately.

**Comment by linbudu599** [comment]
This is supported in esbuild-plugin-clean@0.9.0, you can also refer to the docs: https://nx-plugins.netlify.app/derived/esbuild.html#configuration-2

**Comment by jasonwilliams** [comment]
Thank you for the speedy reply! I will try it out early next week and report back.

**Comment by jasonwilliams** [comment]
Hey I didn't want to make a new issue for this but your copy plugin is also verbose by default. Are you able to switch that to be false by default?

**Comment by linbudu599** [comment]
> Hey I didn't want to make a new issue for this but your copy plugin is also verbose by default. Are you able to switch that to be false by default?

Sure, I used to set verbose option to be `true` by default because this plugin was not stable yet, clear logs help solve problems better, and now I think it can indeed be turned off.

Fixed in `1.3.0`
