### ISSUE TITLE
Cannot find module '@nrwl/workspace/src/command-line/report'

### ISSUE THREAD

**Issue by yemi** [LinbuduLab/nx-plugins#81]
I'm getting this when running `yarn nx generate nx-plugin-esbuild:node-init few --no-interactive --dry-run`:

```
Cannot find module '@nrwl/workspace/src/command-line/report'Cannot find module '@nrwl/workspace/src/command-line/report'
Require stack:
- ~/app/node_modules/nx-plugin-devkit/src/lib/executor-utils/info.js
- ~/app/node_modules/nx-plugin-devkit/src/index.js
- ~/app/node_modules/nx-plugin-esbuild/src/generators/node-init/normalize-schema.js
- ~/app/node_modules/nx-plugin-esbuild/src/generators/node-init/generator.js
- ~/app/node_modules/nx/src/config/workspaces.js
- ~/app/node_modules/nx/src/command-line/generate.js
- ~/app/node_modules/nx/src/command-line/nx-commands.js
- ~/app/node_modules/nx/bin/init-local.js
- ~/app/node_modules/nx/bin/nx.js'fewefw Cannot find module '@nrwl/workspace/src/command-line/report'
```

I'm using `nx: 14.1.4` and `@nrwl/workspace:14.1.5`.

**Comment by alexwine36** [comment]
Same issue here using nx 14.1.7 and prisma generator

**Comment by jcvalerio** [comment]
@alexwine36 / @yemi PR #82 update the Nx dependency to 14.x and will fix your issues

@linbudu599 let me know what you think 👍

**Comment by linbudu599** [comment]
> @alexwine36 / @yemi PR #82 update the Nx dependency to 14.x and will fix your issues
> 
> @linbudu599 let me know what you think 👍

Thanks! But nx 14.x was supported in nx-plugin-vite 2.x version, I'wll mark that as stable to solve related issues.

**Comment by linbudu599** [comment]
The latest 2.2.1 version should make nx-vite works with 14.x workspace now
