### ISSUE TITLE
esbuild-plugin-copy v1.6.0?

### ISSUE THREAD

**Issue by shammahatdivvy** [LinbuduLab/nx-plugins#90]
We recently tried to upgrade esbuild-plugin-copy to 1.5.2 and were running into some problems with our builds. Interestingly, I see that last night 1.6.0 was published on npm. I can't find the changelog anywhere, nor the release tag here, nor any files updated.

Am I confused about who is publishing the plugin now?

**Comment by linbudu599** [comment]
This is weird, I cannot change its visibility to public, when I confirmed the last step GitHub gives me a reload with nothing changed.

**Comment by shammahatdivvy** [comment]
Thanks

**Comment by skyqrose** [comment]
There's a new major version with a changelog, and all the github and npm links are pointing in the right place. Looks like everything's cleaned up, and I'm upgrading to the new one now. Thanks for your work on this package!

https://github.com/LinbuduLab/esbuild-plugins/tree/main/packages/esbuild-plugin-copy
